/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e6d15a06-ab85-4ee9-9a6f-9773a9ca7567

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes a classification system for natural numbers relative to a threshold Î”.
It defines:
- `N Î” x`: A normalization function (returns x if x â‰¥ Î”, else 0).
- `R Î” x`: A remainder function (returns 0 if x â‰¥ Î”, else x).
- `NullClass`: An enumeration with values `zero`, `observable`, `nullified`.
- `classify Î” x`: Classifies x based on Î” (zero if x=0, observable if xâ‰¥Î”, nullified otherwise).

It proves:
- `classification_exhaustive`: The classification covers all cases.
- `classification_unique_*`: The classification categories are mutually exclusive.
- `remainder_when_nullified`: The remainder is x when the class is nullified.
- `remainder_when_observable`: The remainder is 0 when the class is observable.
- `remainder_bound`: The remainder is either 0 or less than Î” (given Î” > 0).
- `R_zero`: The remainder of 0 is 0.
- `conservation`: The sum of the normalization and remainder equals the original number.
- `R_at_threshold`: The remainder at the threshold Î” is 0.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def N (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then x else 0

def R (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then 0 else x

inductive NullClass where
  | zero        
  | observable  
  | nullified   
  deriving DecidableEq, Repr

def classify (Î” : Nat) (x : Nat) : NullClass :=
  if x = 0 then NullClass.zero
  else if x >= Î” then NullClass.observable
  else NullClass.nullified

theorem classification_exhaustive (Î” : Nat) (x : Nat) :
    (classify Î” x = NullClass.zero âˆ¨
     classify Î” x = NullClass.observable âˆ¨
     classify Î” x = NullClass.nullified) := by
  unfold classify; aesop;

theorem classification_unique_zero (Î” : Nat) (x : Nat) :
    classify Î” x = NullClass.zero â†’
    (classify Î” x â‰  NullClass.observable âˆ§ classify Î” x â‰  NullClass.nullified) := by
  aesop

theorem classification_unique_observable (Î” : Nat) (x : Nat) :
    classify Î” x = NullClass.observable â†’
    (classify Î” x â‰  NullClass.zero âˆ§ classify Î” x â‰  NullClass.nullified) := by
  grind

theorem classification_unique_nullified (Î” : Nat) (x : Nat) :
    classify Î” x = NullClass.nullified â†’
    (classify Î” x â‰  NullClass.zero âˆ§ classify Î” x â‰  NullClass.observable) := by
  grind

theorem remainder_when_nullified (Î” : Nat) (x : Nat) :
    classify Î” x = NullClass.nullified â†’ R Î” x = x := by
  unfold classify R at *; aesop;

theorem remainder_when_observable (Î” : Nat) (x : Nat) :
    classify Î” x = NullClass.observable â†’ R Î” x = 0 := by
  unfold classify R;
  grind

theorem remainder_bound (Î” : Nat) (x : Nat) (hÎ” : Î” > 0) :
    R Î” x < Î” âˆ¨ R Î” x = 0 := by
  unfold R; aesop

theorem R_zero (Î” : Nat) : R Î” 0 = 0 := by
  unfold R;
  grind +ring

theorem conservation (Î” : Nat) (x : Nat) : N Î” x + R Î” x = x := by
  unfold N R; split <;> simp

theorem R_at_threshold (Î” : Nat) : R Î” Î” = 0 := by
  unfold R; simp