/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1bf950e3-7fe7-4807-a25d-bc7c43be55af

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the nullification of quark masses below the QCD scale (Î›_QCD = 246 MeV).
It defines the nullification function N and the classification of particles.
It proves that up, down, and strange quarks, as well as the pion, are nullified (mass < Î›_QCD).
It proves that the proton survives (mass > Î›_QCD) and is observable.
It also proves a mass gap theorem stating that any mass is either 0 (nullified) or >= Î›_QCD.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def N (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then x else 0

def R (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then 0 else x

inductive NullClass where
  | zero        
  | observable  
  | nullified   
  deriving DecidableEq, Repr

def classify (Î” : Nat) (x : Nat) : NullClass :=
  if x = 0 then NullClass.zero
  else if x >= Î” then NullClass.observable
  else NullClass.nullified

/-- QCD scale (Î›_QCD) in MeV -/
def Î›_QCD : Nat := 246

/-- Quark masses in MeV (current masses) -/
def m_up : Nat := 2

def m_down : Nat := 5

def m_strange : Nat := 96

def m_charm : Nat := 1270

def m_bottom : Nat := 4180

/-- Hadron masses in MeV -/
def m_pion : Nat := 135

def m_proton : Nat := 938

def m_neutron : Nat := 940

/--
PROVIDED SOLUTION: m_up = 2 < 246 = Î›_QCD, so N returns 0. native_decide or simp.
-/
theorem up_nullified : N Î›_QCD m_up = 0 := by
  -- Since $m_up = 2$ and $\Lambda_{QCD} = 246$, we have $m_up < \Lambda_{QCD}$.
  simp [N, Î›_QCD, m_up]

/--
PROVIDED SOLUTION: m_down = 5 < 246, so N returns 0.
-/
theorem down_nullified : N Î›_QCD m_down = 0 := by
  -- Since $m_{\text{down}} = 5$ and $\Lambda_{\text{QCD}} = 246$, we have $5 < 246$, thus $N(\Lambda_{\text{QCD}}, m_{\text{down}}) = 0$.
  simp [N, Î›_QCD, m_down]

/--
PROVIDED SOLUTION: m_strange = 96 < 246, so N returns 0.
-/
theorem strange_nullified : N Î›_QCD m_strange = 0 := by
  -- Since $m_{\text{strange}} = 96 < 246$, we have $N(Î›_QCD, m_{\text{strange}}) = 0$.
  simp [N, Î›_QCD, m_strange]

/--
PROVIDED SOLUTION: All three quark masses < 246. Unfold, use native_decide.
-/
theorem quarks_nullified :
    N Î›_QCD m_up = 0 âˆ§ N Î›_QCD m_down = 0 âˆ§ N Î›_QCD m_strange = 0 := by
  -- Apply the theorems we have already proven.
  apply And.intro (up_nullified) (And.intro (down_nullified) (strange_nullified))

/--
PROVIDED SOLUTION: 2 â‰  0, 2 < 246. So classify returns nullified. native_decide.
-/
theorem up_is_nullified_class : classify Î›_QCD m_up = NullClass.nullified := by
  -- Since $m_up = 2$ and $\Lambda_{QCD} = 246$, we have $m_up < \Lambda_{QCD}$, so $classify \Lambda_{QCD} m_up = NullClass.nullified$ by definition.
  simp [classify, m_up, Î›_QCD]

/--
PROVIDED SOLUTION: All quarks: mass â‰  0 and mass < 246. native_decide.
-/
theorem quarks_exist :
    classify Î›_QCD m_up = NullClass.nullified âˆ§
    classify Î›_QCD m_down = NullClass.nullified âˆ§
    classify Î›_QCD m_strange = NullClass.nullified := by
  -- By definition of $classify$, we know that for $x < \Lambda_{QCD}$, $classify \Lambda_{QCD} x = \text{nullified}$. Since $m_up$, $m_down$, and $m_strange$ are all less than $\Lambda_{QCD}$, we can apply this definition directly.
  simp [classify, Î›_QCD, m_up, m_down, m_strange]

/--
PROVIDED SOLUTION: m_proton = 938 >= 246, so N returns 938.
-/
theorem proton_survives : N Î›_QCD m_proton = m_proton := by
  -- By definition of $N$, we know that $N(Î›_QCD, m_proton) = m_proton$ since $m_proton \geq Î›_QCD$ and $m_proton$ is in the range of $N$.
  simp [N, Î›_QCD, m_proton]

/--
PROVIDED SOLUTION: 938 â‰  0 and 938 >= 246, so classify returns observable.
-/
theorem proton_observable : classify Î›_QCD m_proton = NullClass.observable := by
  exact?

/--
PROVIDED SOLUTION: m_pion = 135 < 246, so N returns 0.
-/
theorem pion_nullified : N Î›_QCD m_pion = 0 := by
  -- Since 135 < 246, we have N(Î›_QCD, m_pion) = 0.
  simp [N, Î›_QCD, m_pion]

/--
PROVIDED SOLUTION: This is spectral_gap specialized to Î›_QCD.
Unfold N, split, omega.
-/
theorem mass_gap_qcd (x : Nat) :
    N Î›_QCD x = 0 âˆ¨ N Î›_QCD x >= Î›_QCD := by
  -- By definition of $N$, we know that $N Î›_QCD x = 0$ if $x < Î›_QCD$ and $N Î›_QCD x = x$ if $x â‰¥ Î›_QCD$.
  simp [N];
  -- We'll use the fact that if the condition holds, then the result is 0, otherwise it's x.
  by_cases h : Î›_QCD â‰¤ x <;> simp [h]