/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: e6a02d04-ca9e-4289-a8a8-05d56b54a623

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
This module formalizes the properties of a "nullification" function N and a "residue" function R.
It proves theorems regarding distributivity, accumulation, and conservation of sums.
Key results include:
- `distributive_when_both_survive`: N(a) + N(b) = a + b when a, b >= Î”.
- `distributive_sum_survives`: N(a + b) = a + b when a, b >= Î”.
- `non_distributive_example`: Counterexample showing N is not generally distributive.
- `accumulation_possible`: A list of "nullified" elements can sum to a value >= Î”.
- `list_conservation_*`: Theorems showing sumN + sumR = sumList for various cases.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def N (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then x else 0

def R (Î” : Nat) (x : Nat) : Nat := 
  if x >= Î” then 0 else x

inductive NullClass where
  | zero        
  | observable  
  | nullified   
  deriving DecidableEq, Repr

def classify (Î” : Nat) (x : Nat) : NullClass :=
  if x = 0 then NullClass.zero
  else if x >= Î” then NullClass.observable
  else NullClass.nullified

theorem distributive_when_both_survive (Î” : Nat) (a b : Nat)
    (ha : a >= Î”) (hb : b >= Î”) :
    N Î” a + N Î” b = a + b := by
  unfold N; aesop;

theorem distributive_sum_survives (Î” : Nat) (a b : Nat)
    (ha : a >= Î”) (hb : b >= Î”) :
    N Î” (a + b) = a + b := by
  exact if_pos ( by linarith )

theorem non_distributive_example :
    N 10 (6 + 6) â‰  N 10 6 + N 10 6 := by
  decide +revert

theorem six_nullified : N 10 6 = 0 := by
  exact?

theorem twelve_survives : N 10 12 = 12 := by
  decide +revert

def sumR (Î” : Nat) (xs : List Nat) : Nat :=
  xs.foldl (fun acc x => acc + R Î” x) 0

def sumN (Î” : Nat) (xs : List Nat) : Nat :=
  xs.foldl (fun acc x => acc + N Î” x) 0

def sumList (xs : List Nat) : Nat :=
  xs.foldl (Â· + Â·) 0

theorem accumulation_possible :
    âˆƒ (xs : List Nat),
      (âˆ€ x âˆˆ xs, classify 10 x = NullClass.nullified) âˆ§
      sumR 10 xs >= 10 := by
  -- Consider the list [3, 3, 3, 3].
  use [3, 3, 3, 3];
  simp +decide

theorem five_threes_accumulate :
    let xs := [3, 3, 3, 3, 3]
    (âˆ€ x âˆˆ xs, N 10 x = 0) âˆ§ sumR 10 xs = 15 âˆ§ sumR 10 xs >= 10 := by
  native_decide +revert

theorem list_conservation_empty (Î” : Nat) :
    sumN Î” [] + sumR Î” [] = sumList [] := by
  rfl

theorem list_conservation_singleton (Î” : Nat) (x : Nat) :
    sumN Î” [x] + sumR Î” [x] = sumList [x] := by
  cases x <;> simp +decide [ add_comm, sumN, sumR, sumList ];
  Â· unfold N R; aesop;
  Â· unfold N R; aesop;

theorem list_conservation_example :
    sumN 10 [3, 12] + sumR 10 [3, 12] = sumList [3, 12] := by
  native_decide +revert