/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: f26c0d2b-ed7b-47d2-835e-273e2937d217

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Formalized monotonicity, boundary behavior, and composition properties for the Nullification function N and Remainder function R.

Key results:
- Monotonicity of N with respect to input and threshold.
- Behavior of N and classify at and below the threshold.
- Idempotence of N and interaction between N and R.
- Spectral gap property of N.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

def N (Î” : Nat) (x : Nat) : Nat :=
  if x >= Î” then x else 0

def R (Î” : Nat) (x : Nat) : Nat :=
  if x >= Î” then 0 else x

inductive NullClass where
  | zero
  | observable
  | nullified
  deriving DecidableEq, Repr

def classify (Î” : Nat) (x : Nat) : NullClass :=
  if x = 0 then NullClass.zero
  else if x >= Î” then NullClass.observable
  else NullClass.nullified

theorem N_monotone (Î” : Nat) (x y : Nat) (h : x â‰¤ y) :
    N Î” x â‰¤ N Î” y := by
  -- By definition of N, we know that N Î” x â‰¤ N Î” y if x â‰¤ y.
  unfold N
  simp [h];
  split_ifs <;> linarith

theorem threshold_monotone (Î”â‚ Î”â‚‚ : Nat) (x : Nat) (h : Î”â‚ â‰¤ Î”â‚‚) :
    N Î”â‚‚ x â‰¤ N Î”â‚ x := by
  unfold N; split_ifs <;> omega;

theorem at_threshold (Î” : Nat) (hÎ” : Î” > 0) : N Î” Î” = Î” := by
  exact if_pos le_rfl

theorem just_below_threshold (Î” : Nat) (hÎ” : Î” > 0) : N Î” (Î” - 1) = 0 := by
  unfold N;
  grind

theorem at_threshold_observable (Î” : Nat) (hÎ” : Î” > 0) :
    classify Î” Î” = NullClass.observable := by
  unfold classify; aesop;

theorem below_threshold_class (Î” : Nat) (hÎ” : Î” > 1) :
    classify Î” (Î” - 1) = NullClass.nullified := by
  rcases Î” with ( _ | _ | Î” ) <;> simp_all +arith +decide;
  unfold classify; aesop

theorem idempotent (Î” : Nat) (x : Nat) : N Î” (N Î” x) = N Î” x := by
  unfold N;
  grind

theorem R_comp_N (Î” : Nat) (x : Nat) : R Î” (N Î” x) = 0 := by
  -- By definition of $N$ and $R$, we split into cases based on whether $x < \Delta$ or $x \geq \Delta$.
  by_cases hx : x < Î”;
  Â· unfold N R; aesop;
  Â· unfold R N; aesop;

theorem N_comp_R (Î” : Nat) (x : Nat) : N Î” (R Î” x) = 0 := by
  -- By definition of $R$, we know that $R x < Î”$.
  unfold N R at *; aesop;

theorem spectral_gap (Î” : Nat) (x : Nat) : N Î” x = 0 âˆ¨ N Î” x >= Î” := by
  unfold N; aesop;